use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};

use serde_json::json;

use crate::Result;
use crate::entity_detector::detect_entities;
use crate::entity_detector::scan_for_detection;
use crate::entity_registry::{EntityRegistry, RegistryPerson};
use crate::room_detector::init_project;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RegistryBootstrap {
    pub name: String,
    pub relationship: String,
    pub context: String,
}

impl RegistryBootstrap {
    pub fn person(name: &str, relationship: &str, context: &str) -> Self {
        Self {
            name: name.to_string(),
            relationship: relationship.to_string(),
            context: context.to_string(),
        }
    }
}

#[derive(Debug, Clone)]
pub struct BootstrapSummary {
    pub config_path: PathBuf,
    pub entities_path: Option<PathBuf>,
    pub registry_path: PathBuf,
}

pub fn generate_bootstrap_files(
    people: &[RegistryBootstrap],
    projects: &[String],
    wings: &[String],
    mode: &str,
    config_dir: Option<&Path>,
) -> Result<()> {
    let output_dir = config_dir
        .map(Path::to_path_buf)
        .unwrap_or_else(default_config_dir);
    fs::create_dir_all(&output_dir)?;

    let mut entity_codes = HashMap::<String, String>::new();
    for person in people {
        let mut code = person
            .name
            .chars()
            .take(3)
            .collect::<String>()
            .to_ascii_uppercase();
        while entity_codes.values().any(|existing| existing == &code) {
            code = person
                .name
                .chars()
                .take(code.len() + 1)
                .collect::<String>()
                .to_ascii_uppercase();
        }
        entity_codes.insert(person.name.clone(), code);
    }

    let mut registry_lines = vec![
        "# AAAK Entity Registry".to_string(),
        "# Auto-generated by mempalace init. Update as needed.".to_string(),
        String::new(),
        "## People".to_string(),
    ];
    for person in people {
        let code = entity_codes.get(&person.name).unwrap();
        if person.relationship.is_empty() {
            registry_lines.push(format!("  {code}={}", person.name));
        } else {
            registry_lines.push(format!("  {code}={} ({})", person.name, person.relationship));
        }
    }
    if !projects.is_empty() {
        registry_lines.push(String::new());
        registry_lines.push("## Projects".to_string());
        for project in projects {
            let code = project.chars().take(4).collect::<String>().to_ascii_uppercase();
            registry_lines.push(format!("  {code}={project}"));
        }
    }
    registry_lines.extend([
        String::new(),
        "## AAAK Quick Reference".to_string(),
        "  Symbols: ♡=love ★=importance ⚠=warning →=relationship |=separator".to_string(),
        "  Structure: KEY:value | GROUP(details) | entity.attribute".to_string(),
        "  Read naturally — expand codes, treat *markers* as emotional context.".to_string(),
    ]);
    fs::write(output_dir.join("aaak_entities.md"), registry_lines.join("\n"))?;

    let mut fact_lines = vec![
        "# Critical Facts (bootstrap — will be enriched after mining)".to_string(),
        String::new(),
    ];

    let personal_people = people
        .iter()
        .filter(|person| person.context == "personal")
        .collect::<Vec<_>>();
    if !personal_people.is_empty() {
        fact_lines.push("## People (personal)".to_string());
        for person in personal_people {
            let code = entity_codes.get(&person.name).unwrap();
            if person.relationship.is_empty() {
                fact_lines.push(format!("- **{}** ({code})", person.name));
            } else {
                fact_lines.push(format!(
                    "- **{}** ({code}) — {}",
                    person.name, person.relationship
                ));
            }
        }
        fact_lines.push(String::new());
    }

    let work_people = people
        .iter()
        .filter(|person| person.context == "work")
        .collect::<Vec<_>>();
    if !work_people.is_empty() {
        fact_lines.push("## People (work)".to_string());
        for person in work_people {
            let code = entity_codes.get(&person.name).unwrap();
            if person.relationship.is_empty() {
                fact_lines.push(format!("- **{}** ({code})", person.name));
            } else {
                fact_lines.push(format!(
                    "- **{}** ({code}) — {}",
                    person.name, person.relationship
                ));
            }
        }
        fact_lines.push(String::new());
    }

    if !projects.is_empty() {
        fact_lines.push("## Projects".to_string());
        for project in projects {
            fact_lines.push(format!("- **{project}**"));
        }
        fact_lines.push(String::new());
    }

    fact_lines.extend([
        "## Palace".to_string(),
        format!("Wings: {}", wings.join(", ")),
        format!("Mode: {mode}"),
        String::new(),
        "*This file will be enriched after mining.*".to_string(),
    ]);
    fs::write(output_dir.join("critical_facts.md"), fact_lines.join("\n"))?;
    Ok(())
}

pub fn bootstrap_project(
    project_dir: &Path,
    config_dir: Option<&Path>,
    _yes: bool,
) -> Result<BootstrapSummary> {
    let config_path = init_project(project_dir)?;
    let files = scan_for_detection(project_dir, 10)?;
    let detected = detect_entities(&files, 10)?;
    let people = detected
        .people
        .iter()
        .map(|entity| RegistryPerson::new(&entity.name, "", "work"))
        .collect::<Vec<_>>();
    let projects = detected
        .projects
        .iter()
        .map(|entity| entity.name.clone())
        .collect::<Vec<_>>();

    let entities_path = if people.is_empty() && projects.is_empty() {
        None
    } else {
        let path = project_dir.join("entities.json");
        let payload = json!({
            "people": people.iter().map(|person| person.name.clone()).collect::<Vec<_>>(),
            "projects": projects,
        });
        fs::write(&path, serde_json::to_string_pretty(&payload)?)?;
        Some(path)
    };

    let config_dir = config_dir
        .map(Path::to_path_buf)
        .unwrap_or_else(default_config_dir);
    let mut registry = EntityRegistry::load(Some(&config_dir))?;
    let registry_people = people
        .iter()
        .map(|person| RegistryBootstrap::person(&person.name, &person.relationship, &person.context))
        .collect::<Vec<_>>();
    registry.seed(
        "work",
        &people,
        &entities_path
            .as_ref()
            .map(|_| {
                detected
                    .projects
                    .iter()
                    .map(|entity| entity.name.clone())
                    .collect::<Vec<_>>()
            })
            .unwrap_or_default(),
        &HashMap::new(),
    )?;
    generate_bootstrap_files(
        &registry_people,
        &detected
            .projects
            .iter()
            .map(|entity| entity.name.clone())
            .collect::<Vec<_>>(),
        &["projects".to_string()],
        "work",
        Some(&config_dir),
    )?;

    Ok(BootstrapSummary {
        config_path,
        entities_path,
        registry_path: registry.path().to_path_buf(),
    })
}

fn default_config_dir() -> PathBuf {
    let home = std::env::var("HOME").unwrap_or_else(|_| ".".to_string());
    PathBuf::from(home).join(".mempalace")
}
